### ISSUE TITLE
Overriding default security headers not working

### ISSUE THREAD

**Issue by mheadd** [cloud-gov/cg-secureproxy-boshrelease#61]
Various [security-related HTTP headers](https://cloud.gov/docs/management/headers/) are set which a user should be able to override by having their application return different values. This override process does not appear to work, at least for applications using the `Staticfile` buildpack.

**Comment by folksgl** [comment]
@mheadd and @bengerman13 has there been any update on this bug?

**Comment by folksgl** [comment]
@bengerman13 This issue is being raised again by security/scan teams - has implementation of a fix begun?

**Comment by bengerman13** [comment]
@folksgl it hasn't, although I've been in this codebase for other things in the last week or so. I'll try to take a look today.

dropping this from the original report on slack so it's easier to track:

> when I attempt to validate the settings externally via `curl -v https://<my-staticfile-app>.cloud.gov` and the `strict-transport-security` header remains unmodified, with a value of `strict-transport-security: max-age=31536000` instead of the expected value `Strict-Transport-Security: max-age=31536000; includeSubDomains; preload` as documented in the [Cloud Foundry Staticfile Buildpack](https://docs.cloudfoundry.org/buildpacks/staticfile/) docs.

The upshot is it appears we're messing with the `strict-transport-security` header even when it's set, which we should not be doing and is not what we say we do. 

(please let me know if you're seeing this elsewhere - this is handled differently for different headers)

**Comment by bengerman13** [comment]
@folksgl I made indirect progress today by writing an integration test suite for headers in cf: https://github.com/cloud-gov/cg-deploy-cf/pull/678

**Comment by bengerman13** [comment]
@folksgl the tests I wrote all passed, so this appears to be working for me. Can you share a minimal repro, or reach out to support for more troubleshooting on your running app?

**Comment by mogul** [comment]
If you're doing anything other than just serving a directory full of static
HTML, JS, CSS and media assets, yes.

**Comment by folksgl** [comment]
So I ssh'd to my test app...

>
    cf ssh hsts-header-test
    vcap@GUID:~$ curl -I localhost:8080/
    HTTP/1.1 200 OK
    Server: nginx
    Date: Thu, 02 Jun 2022 15:18:47 GMT
    Content-Type: text/html; charset=utf-8
    Content-Length: 103
    Last-Modified: Thu, 02 Jun 2022 14:29:28 GMT
    Connection: keep-alive
    ETag: "6298c948-67"
    Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
    Accept-Ranges: bytes

**Comment by mogul** [comment]
That definitely looks platform-side.

**Comment by folksgl** [comment]
Here is the minimal Python example, which actually **does** work as expected. HSTS headers are correct when visited using the generated `app.cloud.gov` URL.

Manifest:

```yaml
---
version: 1
applications:
  - name: hsts-python-test
    random-route: true
    memory: 64M
    instances: 1
    buildpacks:
      - python_buildpack
    command: uvicorn main:app --host 0.0.0.0 --port $PORT
```

requirements.txt
```text
fastapi
uvicorn
```

main.py
```python
from fastapi import FastAPI, Response

app = FastAPI()

HSTS_HEADER = "Strict-Transport-Security"
HSTS_EXPECTED_VALUE = "max-age=63072000; includeSubDomains; preload"


@app.get("/")
def read_root(response: Response):
    response.headers[HSTS_HEADER] = HSTS_EXPECTED_VALUE
    return {"Hello": "World"}
```

So there's different behavior based on these two Buildpacks at the very least.

**Comment by folksgl** [comment]
Minimal Python example, which actually **does** work as expected as of the time of writing. HSTS headers are correct when visited using the generated `app.cloud.gov` URL.

Manifest:

```yaml
---
version: 1
applications:
  - name: hsts-python-test
    random-route: true
    memory: 64M
    instances: 1
    buildpacks:
      - python_buildpack
    command: uvicorn main:app --host 0.0.0.0 --port $PORT
```

requirements.txt
```text
fastapi
uvicorn
```

main.py
```python
from fastapi import FastAPI, Response

app = FastAPI()

HSTS_HEADER = "Strict-Transport-Security"
HSTS_EXPECTED_VALUE = "max-age=63072000; includeSubDomains; preload"


@app.get("/")
def read_root(response: Response):
    response.headers[HSTS_HEADER] = HSTS_EXPECTED_VALUE
    return {"Hello": "World"}
```
